---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapplication-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapplication
  template:
    metadata:
      labels:
        app: myapplication
    spec:
      containers:
      - name: myapplication
        image: myapplication:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
      imagePullSecrets:
      - name: myregistrykey
---
apiVersion: v1
kind: Service
metadata:
  name: myapplication-service
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: myapplication
